config/routes.rb
Rails.application.routes.draw do
  resources :syohins

end

app/models/syohin.rb
class Syohin < ActiveRecord::Base
  before_update do
    self.kingaku = kingaku.round(-1)
    self.record_datetime += 1.day
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/syohins_controller.rb
class SyohinsController < ApplicationController
  before_action :set_syohin, only: [:show, :edit, :update, :destroy]

  # GET /syohins
  # GET /syohins.json
  def index
    @syohins = Syohin.all
  end

  # GET /syohins/1
  # GET /syohins/1.json
  def show
  end

  # GET /syohins/new
  def new
    @syohin = Syohin.new
  end

  # GET /syohins/1/edit
  def edit
  end

  # POST /syohins
  # POST /syohins.json
  def create
    @syohin = Syohin.new(syohin_params)

    respond_to do |format|
      if @syohin.save
        format.html { redirect_to @syohin, notice: 'Syohin was successfully created.' }
        format.json { render :show, status: :created, location: @syohin }
      else
        format.html { render :new }
        format.json { render json: @syohin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /syohins/1
  # PATCH/PUT /syohins/1.json
  def update
    respond_to do |format|
      if @syohin.update(syohin_params)
        format.html { redirect_to @syohin, notice: 'Syohin was successfully updated.' }
        format.json { render :show, status: :ok, location: @syohin }
      else
        format.html { render :edit }
        format.json { render json: @syohin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /syohins/1
  # DELETE /syohins/1.json
  def destroy
    @syohin.destroy
    respond_to do |format|
      format.html { redirect_to syohins_url, notice: 'Syohin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_syohin
      @syohin = Syohin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def syohin_params
      params.require(:syohin).permit(:kingaku, :record_datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/syohins_helper.rb
module SyohinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ModifiendUpdateRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/syohins/_form.html.erb
<%= form_for(@syohin) do |f| %>
  <% if @syohin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@syohin.errors.count, "error") %> prohibited this syohin from being saved:</h2>

      <ul>
      <% @syohin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kingaku %><br>
    <%= f.number_field :kingaku %>
  </div>
  <div class="field">
    <%= f.label :record_datetime %><br>
    <%= f.datetime_select :record_datetime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/syohins/edit.html.erb
<h1>Editing syohin</h1>

<%= render 'form' %>

<%= link_to 'Show', @syohin %> |
<%= link_to 'Back', syohins_path %>

app/views/syohins/index.html.erb
<h1>Listing syohins</h1>

<table>
  <thead>
    <tr>
      <th>Kingaku</th>
      <th>Record datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @syohins.each do |syohin| %>
      <tr>
        <td><%= syohin.kingaku %></td>
        <td><%= syohin.record_datetime %></td>
        <td><%= link_to 'Show', syohin %></td>
        <td><%= link_to 'Edit', edit_syohin_path(syohin) %></td>
        <td><%= link_to 'Destroy', syohin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Syohin', new_syohin_path %>

app/views/syohins/new.html.erb
<h1>New syohin</h1>

<%= render 'form' %>

<%= link_to 'Back', syohins_path %>

app/views/syohins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kingaku:</strong>
  <%= @syohin.kingaku %>
</p>

<p>
  <strong>Record datetime:</strong>
  <%= @syohin.record_datetime %>
</p>

<%= link_to 'Edit', edit_syohin_path(@syohin) %> |
<%= link_to 'Back', syohins_path %>